# Production 

version: '3.9'
services:
  api:
  container_name: food_api
  build: .
  restart: always
  env_file: .venv
  ports:
    - "8000:8000"
  command: >
    sh -c " python manage.py migrate &&
        gunicorn restaurant.wsgi:application --bind 0.0.0.0:8000"
  volumes:
    - .:/app
