# Generated by Django 4.2.2 on 2023-06-24 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishmentName', models.CharField(max_length=255)),
                ('openingHours', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stallName', models.CharField(max_length=255)),
                ('establishmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_item.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=255)),
                ('establishmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_item.establishment')),
                ('genreId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_item.genre')),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_item.location')),
                ('stallId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_item.stall')),
            ],
        ),
        migrations.AddField(
            model_name='establishment',
            name='locationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_item.location'),
        ),
    ]
